{{/*
apiVersion: v1
kind: Service
metadata:
  name: {{ default "app-default" .Values.service.name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
*/}}