{{/*
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}-service"
spec:
  {{- if .Values.cong }}
  config:
    {{- toYaml .Values.cong | nindent 4 }}
  {{- else if .Values.cong2 }}
  config:
    {{- toYaml .Values.cong2 | nindent 4 }}
  {{- else }}
  config: "null"
  {{- end }}
*/}}