{{/*
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service }}
  name: {{ .Values.service.name }}-service
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
*/}}