{{/*
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ and .Values.service.type .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
*/}}